//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gendarme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plainte
    {
        public int idPlainte { get; set; }
        public string idOmby { get; set; }
        public string lieuPlainte { get; set; }

        [JsonDateFormat("dd-MM-yyyy")]
        public Nullable<System.DateTime> datePlainte { get; set; }
        public string lieuResolution { get; set; }

        [JsonDateFormat("dd-MM-yyyy")]
        public Nullable<System.DateTime> dateResolution { get; set; }
    }

    [AttributeUsage(AttributeTargets.Property, Inherited = false, AllowMultiple = false)]
    sealed class JsonDateFormatAttribute : Attribute
    {
        public JsonDateFormatAttribute(string format)
        {
            Format = format;
        }

        public string Format { get; }
    }
}
