//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gendarme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plainte
    {
        public int idPlainte { get; set; }
        public string idOmby { get; set; }
        public string lieuPlainte { get; set; }
        public Nullable<System.DateTime> datePlainte { get; set; }
        public string lieuResolution { get; set; }
        public Nullable<System.DateTime> dateResolution { get; set; }
    }
}
